jobs:
  include:
    - lanuage: python

      python:
        - "3.7"

      install:
        - pip install -r requirements.txt

      before_script: cd backend

      script:
        - pytest -v ./*_tests.py

    - language: node_js

      node_js:
        - 12

      before_install: cd frontend

      script:
        - npm test
